name: backup

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  backup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Setup a Go environment and add it to the PATH
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.16.5'

      # Get the toolset
      - name: Get the toolset
        run: go get github.com/zhuochun/notion-toolset

      # Runs backup commands
      - name: Export database
        run: notion-toolset --config=configs/export.yaml --cmd=export
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      # Commit changes to repo
      # Update your repo: Settings > Actions > General > Enable "Read and write permissions"
      - name: Commit exported files
        run: |
          git config user.name notion-toolset
          git config user.email notion-toolset@github.action
          git add --all
          git commit -m "Auto backup $(date +'%Y-%m-%d %T')"
          git push