name: daily-jobs
# Controls when the action will run.
on:
  # Run the daily job every day at midnight UTC
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flashback:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup a Go environment and add it to the PATH
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      # Get the toolset
      - name: Get the toolset
        run: go get github.com/zhuochun/notion-toolset

      # Run the go app
      - name: Run flashback cmd
        run: notion-toolset --config=configs/flashback.yaml --cmd=flashback
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}